import { stringify as stringifyToml } from 'smol-toml';

import {
  claudeAgentFrontmatter,
  impliedSandboxMode,
  type ParsedAgentFile,
} from './agent-frontmatter.js';
import { GENERATED_MARKER } from './emit.js';
import { applyCodexFallbacks } from './fallback.js';
import { serializeFrontmatter, type Target } from './frontmatter.js';
import { renderConditionals } from './template.js';

/** The TOML-comment form of the ownership marker, for Codex agent files. */
export const GENERATED_MARKER_TOML = `# generated by skillset — do not edit; edit the source in your skillset directory`;

function toolList(tools: string | string[] | undefined): string | undefined {
  if (tools === undefined) return undefined;

  return Array.isArray(tools) ? tools.join(', ') : tools;
}

/**
 * Codex has no structured per-agent tool allowlist, so Claude's `tools` /
 * `disallowedTools` become a short prose section appended to the
 * developer instructions.
 */
function toolGuidance(parsed: ParsedAgentFile): string {
  const allowed = toolList(parsed.frontmatter.tools);
  const disallowed = toolList(parsed.frontmatter.disallowedTools);
  if (!allowed && !disallowed) return '';

  const lines = ['', '## Tool guidance', ''];
  if (allowed) lines.push(`Only use these tools: ${allowed}.`);
  if (disallowed) lines.push(`Never use these tools: ${disallowed}.`);

  return lines.join('\n');
}

function renderBody(parsed: ParsedAgentFile, target: Target): string {
  const rendered = renderConditionals(parsed.body, target);
  if (rendered.errors.length > 0) {
    throw new Error(`template errors: ${rendered.errors.map((error) => error.message).join('; ')}`);
  }

  return rendered.body;
}

/** Compile an agent for Claude Code: frontmatter projection + marker + body. */
export function emitClaudeAgent(parsed: ParsedAgentFile): string {
  const fields = claudeAgentFrontmatter(parsed.frontmatter);
  const body = renderBody(parsed, 'claude');

  return `${serializeFrontmatter(fields)}\n${GENERATED_MARKER}\n\n${body.replace(/^\n+/, '')}`;
}

/**
 * Serialize a multi-line string as a TOML literal block when possible,
 * falling back to smol-toml's escaped basic string when the body itself
 * contains a `'''` delimiter.
 */
function tomlMultilineString(value: string): string {
  if (value.includes("'''")) return stringifyToml({ value }).replace(/^value = /, '');

  return `'''\n${value}\n'''`;
}

/**
 * Compile an agent for Codex: a standalone `~/.codex/agents/<name>.toml` with
 * the body (rendered for the codex target, Claude-only dynamic features
 * rewritten as prose) as `developer_instructions`, plus the `codex:` block's
 * model/sandbox settings. A Claude `permissionMode` of `plan`/`acceptEdits`
 * implies `sandbox_mode` when the `codex:` block doesn't set one.
 */
function codexScalarFields(parsed: ParsedAgentFile): Record<string, unknown> {
  const { frontmatter } = parsed;
  const codex = frontmatter.codex ?? {};

  const fields: Record<string, unknown> = {
    name: frontmatter.name,
    description: frontmatter.description,
  };
  if (codex.model) fields['model'] = codex.model;
  if (codex.model_reasoning_effort) {
    fields['model_reasoning_effort'] = codex.model_reasoning_effort;
  }
  if (codex.model_verbosity) fields['model_verbosity'] = codex.model_verbosity;

  const sandboxMode = codex.sandbox_mode ?? impliedSandboxMode(frontmatter.permissionMode);
  if (sandboxMode) fields['sandbox_mode'] = sandboxMode;
  if (codex.nickname_candidates) fields['nickname_candidates'] = codex.nickname_candidates;

  return fields;
}

function codexTableFields(parsed: ParsedAgentFile): Record<string, unknown> {
  const codex = parsed.frontmatter.codex ?? {};
  const fields: Record<string, unknown> = {};

  for (const key of ['hooks', 'mcp_servers', 'skills', 'tools'] as const) {
    if (codex[key] !== undefined) fields[key] = codex[key];
  }

  return fields;
}

export function emitCodexAgent(parsed: ParsedAgentFile): string {
  const body = applyCodexFallbacks(renderBody(parsed, 'codex'), []).body;
  const instructions = `${body.replace(/^\n+/, '').trimEnd()}${toolGuidance(parsed)}`;

  // TOML requires every top-level scalar (including developer_instructions)
  // to appear before the first table header, so tables are emitted last.
  const tableFields = codexTableFields(parsed);

  const parts = [
    GENERATED_MARKER_TOML,
    stringifyToml(codexScalarFields(parsed)),
    `developer_instructions = ${tomlMultilineString(instructions)}`,
  ];
  if (Object.keys(tableFields).length > 0) parts.push('', stringifyToml(tableFields).trimEnd());

  return `${parts.join('\n')}\n`;
}
