import { applyCodexFallbacks, argumentNames } from './fallback.js';
import {
  claudeFrontmatter,
  codexFrontmatter,
  openaiConfiguration,
  serializeFrontmatter,
  serializeOpenaiConfiguration,
  type ParsedSkillFile,
  type Target,
} from './frontmatter.js';
import { renderConditionals } from './template.js';

/**
 * The ownership marker written into every generated SKILL.md. Its presence is
 * what allows a later sync to overwrite or prune a target directory; files
 * without it are treated as hand-installed and left alone.
 */
export const GENERATED_MARKER =
  '<!-- generated by skillset — do not edit; edit the source in your skillset directory -->';

/** One file of a compiled skill, as a path relative to the skill directory. */
export type EmittedFile = {
  relativePath: string;
  contents: string;
};

/**
 * Compile a parsed skill for one target: project the frontmatter, render the
 * body's conditionals, apply the Codex fallbacks when targeting Codex, stamp
 * the ownership marker, and (for Codex) serialize `agents/openai.yaml`.
 *
 * @throws {Error} If the body has structural template errors — callers are
 * expected to have run the template validation (via doctor) first.
 */
export function emitSkill(skill: ParsedSkillFile, target: Target): EmittedFile[] {
  const rendered = renderConditionals(skill.body, target);
  if (rendered.errors.length > 0) {
    throw new Error(`template errors: ${rendered.errors.map((error) => error.message).join('; ')}`);
  }

  let body = rendered.body;
  if (target === 'codex') {
    body = applyCodexFallbacks(body, argumentNames(skill.frontmatter.arguments)).body;
  }

  const fields =
    target === 'claude'
      ? claudeFrontmatter(skill.frontmatter)
      : codexFrontmatter(skill.frontmatter);
  const skillFile = `${serializeFrontmatter(fields)}\n${GENERATED_MARKER}\n\n${body.replace(/^\n+/, '')}`;

  const files: EmittedFile[] = [{ relativePath: 'SKILL.md', contents: skillFile }];

  if (target === 'codex') {
    const configuration = openaiConfiguration(skill.frontmatter);
    if (configuration) {
      files.push({
        relativePath: 'agents/openai.yaml',
        contents: serializeOpenaiConfiguration(configuration),
      });
    }
  }

  return files;
}
