import { describe, expect, it } from 'bun:test';

import {
  GENERATED_MARKER,
  parseAgentFile,
  parseEnvironment,
  parseMcpSource,
  parseSkillFile,
  runCli,
} from './index.js';

it('loads the test preload', () => {
  expect((globalThis as Record<string, unknown>)['__BUN_TEST_SETUP_LOADED__']).toBe(true);
});

describe('public surface', () => {
  it('re-exports the CLI and compiler primitives', () => {
    expect(typeof runCli).toBe('function');
    expect(typeof parseSkillFile).toBe('function');
    expect(typeof parseAgentFile).toBe('function');
    expect(typeof parseMcpSource).toBe('function');
    expect(GENERATED_MARKER).toContain('generated by skillset');
  });
});

describe('parseEnvironment', () => {
  it('applies defaults when variables are absent', () => {
    const environment = parseEnvironment({});
    expect(environment.NODE_ENV).toBe('development');
    expect(environment.SKILLSET_DIRECTORY).toBeUndefined();
  });

  it('passes SKILLSET_DIRECTORY through', () => {
    expect(parseEnvironment({ SKILLSET_DIRECTORY: '/x' }).SKILLSET_DIRECTORY).toBe('/x');
  });

  it('rejects an unknown NODE_ENV', () => {
    expect(() => parseEnvironment({ NODE_ENV: 'staging' })).toThrow();
  });
});
