import chalk from 'chalk';

import type { EmbeddedAction } from './config-files.js';
import type { AgentReport, Issue, SkillReport } from './doctor.js';
import type { SyncAction } from './sync.js';

/** Render one source's doctor verdict as a check/cross line plus its issues. */
export function renderIssues(name: string, issues: Issue[], log: (line: string) => void): void {
  if (issues.length === 0) {
    log(`${chalk.green('✓')} ${name}`);
    return;
  }

  log(`${chalk.red('✗')} ${name}`);
  for (const issue of issues) {
    const label = issue.severity === 'error' ? chalk.red('error') : chalk.yellow('warning');
    log(`  ${label} ${issue.message}`);
  }
}

function renderVerb(verb: SyncAction['action']): string {
  return {
    write: chalk.green('write'),
    overwrite: chalk.cyan('overwrite'),
    'skip-unmanaged': chalk.yellow('skip (not generated by skillset — use --force)'),
    'skip-drifted': chalk.yellow('skip (hand-edited since last sync — use --force to overwrite)'),
    prune: chalk.red('prune'),
  }[verb];
}

/** One line of sync output for a skill or agent action. */
export function renderSyncAction(action: SyncAction): string {
  return `${renderVerb(action.action)} ${action.target} ${action.kind} ${action.name}: ${action.path}`;
}

/** One line of sync output for an action embedded in a shared config file. */
export function renderEmbeddedAction(action: EmbeddedAction): string {
  return `${renderVerb(action.action)} ${action.target} ${action.kind} ${action.name}: ${action.file}`;
}

/** Everything the doctor renderer needs. */
export type DoctorRendering = {
  skillReports: SkillReport[];
  agentReports: AgentReport[];
  /** Per-source-file issue groups, keyed by display name; absent files omitted. */
  files: Record<string, Issue[]>;
};

/** Render the doctor report as text or `--json`. */
export function renderDoctor(
  rendering: DoctorRendering,
  json: boolean,
  log: (line: string) => void,
): void {
  if (json) {
    log(
      JSON.stringify(
        {
          skills: rendering.skillReports.map(({ name, issues }) => ({ name, issues })),
          agents: rendering.agentReports.map(({ name, issues }) => ({ name, issues })),
          files: rendering.files,
        },
        undefined,
        2,
      ),
    );
    return;
  }

  for (const report of rendering.skillReports) {
    renderIssues(`skill ${report.name}`, report.issues, log);
  }
  for (const report of rendering.agentReports) {
    renderIssues(`agent ${report.name}`, report.issues, log);
  }
  for (const [name, issues] of Object.entries(rendering.files)) {
    renderIssues(name, issues, log);
  }
}
